// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportJSON(arg1) {
  return window['go']['backend']['App']['ExportJSON'](arg1);
}

export function Start(arg1) {
  return window['go']['backend']['App']['Start'](arg1);
}
